Repository RedHatInsights/curiosity-frontend, pull requests merged in 2023-10, with the labels that each got.

#1207 docs(contributing): sw-1792 update release steps
  CONTRIBUTING.md
  config/cspell.config.json
Labels: 202312

#1208 docs(config): allow generated readme
  scripts/actions.commit.js
  scripts/readme.docs.js
  src/config/README.md
  src/config/product.openshiftContainer.js
  src/config/product.openshiftDedicated.js
  src/config/product.openshiftMetrics.js
  src/config/product.rhacs.js
  src/config/product.rhel.js
  src/config/product.rhods.js
  src/config/product.rosa.js
  src/config/product.satellite.js
  src/config/products.js
  src/config/routes.js
  tests/__snapshots__/code.test.js.snap
Labels: 202312

#1212 build(eslint): limit comment line length
  .eslintrc
  package.json
  src/common/README.md
  src/common/helpers.js
  src/components/README.md
  src/components/form/select.js
  src/components/table/table.js
  src/components/toolbar/toolbar.js
  src/config/README.md
  src/config/product.openshiftContainer.js
  src/config/product.openshiftDedicated.js
  src/config/product.rhacs.js
  src/config/product.rhel.js
  src/config/product.rhods.js
  src/config/product.rosa.js
  src/config/product.satellite.js
  src/config/products.js
  src/services/README.md
  src/services/common/__tests__/serviceConfig.test.js
  src/services/rhsm/rhsmConstants.js
  src/services/rhsm/rhsmTransformers.js
  yarn.lock
Labels: build, 202312

#1214 build(eslint): add lintfix script
  package.json
Labels: build, 202312

#1221 fix(build): sw-1885 rollback to beta prefix
  scripts/pre.sh
Labels: bug, platform, build, 202312

#1225 feat(config): SWATCH-1890 activate rhel for x86 HA
  public/locales/en-US.json
  src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap
  src/services/rhsm/rhsmConstants.js
  tests/__snapshots__/dist.test.js.snap
Labels: 202312
