Repository RedHatInsights/curiosity-frontend, pull requests merged in 2023-08, with the labels that each got.

#1161 refactor(config): sw-1565 remove rhosak
  public/locales/en-US.json
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/config/__tests__/__snapshots__/product.rhosak.test.js.snap
  src/config/__tests__/__snapshots__/products.test.js.snap
  src/config/__tests__/product.rhosak.test.js
  src/config/product.rhosak.js
  src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap
  src/services/rhsm/rhsmConstants.js
  tests/__snapshots__/dist.test.js.snap
Labels: 202308

#1156 2 of 2 - refactor(rhsmServices): sw-870 remove, replace hosts refs
  .env
  .env.development
  public/locales/en-US.json
  src/common/README.md
  src/common/__tests__/__snapshots__/helpers.test.js.snap
  src/common/helpers.js
  src/components/README.md
  src/components/inventoryCard/__tests__/__snapshots__/inventoryCardContext.test.js.snap
  src/components/inventoryCard/__tests__/__snapshots__/inventoryCardHosts.test.js.snap
  src/components/inventoryCard/__tests__/inventoryCardContext.test.js
  src/components/inventoryCard/__tests__/inventoryCardHosts.test.js
  src/components/inventoryCard/inventoryCard.js
  src/components/inventoryCard/inventoryCardContext.js
  src/components/inventoryCard/inventoryCardHosts.js
  src/components/productView/productViewContext.js
  src/config/__tests__/product.rhacs.test.js
  src/config/__tests__/product.rhods.test.js
  src/redux/README.md
  src/redux/actions/__tests__/rhsmActions.test.js
  src/redux/actions/rhsmActions.js
  src/redux/reducers/__tests__/__snapshots__/inventoryReducer.test.js.snap
  src/redux/reducers/__tests__/inventoryReducer.test.js
  src/redux/reducers/inventoryReducer.js
  src/redux/types/__tests__/__snapshots__/index.test.js.snap
  src/redux/types/queryTypes.js
  src/redux/types/rhsmTypes.js
  src/services/README.md
  src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap
  src/services/rhsm/__tests__/__snapshots__/rhsmSchemas.test.js.snap
  src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap
  src/services/rhsm/__tests__/rhsmServices.test.js
  src/services/rhsm/__tests__/rhsmTransformers.test.js
  src/services/rhsm/rhsmConstants.js
  src/services/rhsm/rhsmSchemas.js
  src/services/rhsm/rhsmServices.js
  src/services/rhsm/rhsmTransformers.js
  tests/__snapshots__/code.test.js.snap
  tests/__snapshots__/dist.test.js.snap
Labels: 202308

#1165 fix(toolbarFilter): pf wrapper, expand conditional checks
  src/components/README.md
  src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFilter.test.js.snap
  src/components/toolbar/__tests__/toolbarFilter.test.js
  src/components/toolbar/toolbar.js
  src/components/toolbar/toolbarFilter.js
  tests/__snapshots__/dist.test.js.snap
Labels: patternfly, 202308

#1051 chore(build): ephemeral rename, nav items
  deploy/frontend.yaml
  tests/__snapshots__/dist.test.js.snap
Labels: build, 202304, 202308

#1072 chore(build): run QE tests during PR workflow
  deploy/pr_check.sh
Labels: build, 202304, 202308

#1170 fix(services): sw-1605 mock update for deprecated ids
  src/services/rhsm/rhsmServices.js
Labels: 202308

#1176 chore(build): Update pr_checks with rp and ibutsu options
  deploy/pr_check.sh
Labels: build, 202308

#1177 chore(build): sw-1647 workflow mod, prep for branch rename
  .github/dependabot.yml
  .github/workflows/pull_request.yml
  .travis.yml
  .travis/custom_release.sh
  CONTRIBUTING.md
Labels: build, 202308

#1180 chore(build): sw-1647 deployment env variable
  config/webpack.prod.config.js
  scripts/pre.sh
Labels: build, 202308
