Repository RedHatInsights/curiosity-frontend, pull requests merged in 2023-07, with the labels that each got.

#1146 1 of 3 - refactor(minHeight): sw-1348 class to func
  src/components/README.md
  src/components/graphCard/__tests__/__snapshots__/graphCardChart.test.js.snap
  src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap
  src/components/inventoryCard/inventoryCard.js
  src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap
  src/components/minHeight/__tests__/minHeight.test.js
  src/components/minHeight/minHeight.js
Labels: 202308

#1148 2 of 3 - build(babel): sw-1348 update presets, targets
  babel.config.js
  config/build.dotenv.js
  package.json
  src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap
  tests/__snapshots__/dist.test.js.snap
  yarn.lock
Labels: 202308

#1158 add url for new subs bundle
  config/webpack.dev.config.js
  config/webpack.proxy.config.js
Labels: platform, 202308

#1160 fix(config): rhods, app-services default product
  src/config/product.rhods.js
  src/config/product.rhosak.js
  tests/__snapshots__/dist.test.js.snap
Labels: bug, 202308
