Repository RedHatInsights/curiosity-frontend, pull requests merged in 2024-07, with the labels that each got.

#1348 fix: sw-2353 cancel validator when app doesn't exist
  public/locales/en-US.json
  src/components/README.md
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/__tests__/toolbarFieldExportContext.test.js
  src/components/toolbar/toolbarFieldExportContext.js
  src/hooks/README.md
  src/hooks/__tests__/__snapshots__/useApp.test.js.snap
  src/hooks/__tests__/useApp.test.js
  src/hooks/useApp.js
  src/services/platform/platformServices.js
  tests/__snapshots__/dist.test.js.snap
Labels: bug, 202408

#1353 SWATCH-2729: Change custom export notification's data-test for No button
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/toolbarFieldExportContext.js
Labels: env:test, 202408

#1354 fix: sw-2353 reset export state
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/toolbarFieldExportContext.js
  src/redux/reducers/__tests__/__snapshots__/appReducer.test.js.snap
  src/redux/reducers/__tests__/appReducer.test.js
  src/redux/reducers/appReducer.js
  src/redux/types/__tests__/__snapshots__/index.test.js.snap
  src/redux/types/index.js
Labels: bug, 202404

#1355 refactor: sw-2353 onmount, dispatch refinement
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/__tests__/toolbarFieldExportContext.test.js
  src/components/toolbar/toolbarFieldExportContext.js
Labels: 202408

#1358 test(toolbarFieldContext): sw-2353 add notification testIds
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/toolbarFieldExportContext.js
Labels: 202408

#1360 build(deps-dev): bump group with 5 updates
  babel.config.js
  config/webpack.dev.config.js
  package-lock.json
  package.json
  src/styles/_graph.scss
Labels: build, 202408

#1367 feat(toolbarFieldExport): sw-2768 activate instances data
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap
  src/components/toolbar/toolbarFieldExport.js
Labels: 202408

#1369 fix(toolbarFieldExport): sw-117 apply export label
  public/locales/en-US.json
  src/components/README.md
  src/components/form/__tests__/__snapshots__/select.test.js.snap
  src/components/form/select.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingProvider.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldCategory.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldRangedMonthly.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldSelectCategory.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldSla.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldUsage.test.js.snap
  src/components/toolbar/toolbar.js
  src/components/toolbar/toolbarFieldExport.js
  tests/__snapshots__/dist.test.js.snap
Labels: 202408

#1365 refactor(serviceConfig): sw-2353 unified status response
  src/components/toolbar/toolbarFieldExportContext.js
  src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap
  src/services/common/__tests__/serviceConfig.test.js
  src/services/common/serviceConfig.js
  tests/__snapshots__/code.test.js.snap
Labels: 202408

#1373 feat(toolbarFieldExport): sw-2769 activate csv export
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap
  src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
  src/components/toolbar/__tests__/toolbarFieldExportContext.test.js
  src/components/toolbar/toolbarFieldExport.js
  src/components/toolbar/toolbarFieldExportContext.js
  src/redux/reducers/appReducer.js
  src/services/platform/__tests__/__snapshots__/platformConstants.test.js.snap
  src/services/platform/platformConstants.js
Labels: 202408
