Repository RedHatInsights/curiosity-frontend, pull requests merged in 2025-05, with the labels that each got.

#1587 feat(rhsmTransformers,bannerMessages): sw-3519 usage alert banner
  .env
  public/locales/en-US.json
  src/common/README.md
  src/common/__tests__/__snapshots__/helpers.test.js.snap
  src/common/helpers.js
  src/components/README.md
  src/components/bannerMessages/__tests__/__snapshots__/bannerMessagesContext.test.js.snap
  src/components/bannerMessages/__tests__/bannerMessagesContext.test.js
  src/components/bannerMessages/bannerMessagesContext.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/productView/__tests__/__snapshots__/productViewOnloadContext.test.js.snap
  src/components/productView/productViewOnload.js
  src/components/productView/productViewOnloadContext.js
  src/services/README.md
  src/services/rhsm/__tests__/__snapshots__/rhsmHelpers.test.js.snap
  src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap
  src/services/rhsm/__tests__/rhsmHelpers.test.js
  src/services/rhsm/rhsmHelpers.js
  src/services/rhsm/rhsmTransformers.js
  tests/__snapshots__/code.test.js.snap
  tests/__snapshots__/dist.test.js.snap
Labels: 202504

#1597 fix(rhsmHelpers): sw-3519 expose unique accounts, providers
  src/services/rhsm/__tests__/__snapshots__/rhsmHelpers.test.js.snap
  src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap
  src/services/rhsm/rhsmHelpers.js
Labels: 202504

#1598 fix(locale): sw-3519 unique provider names context
  public/locales/en-US.json
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/productView/productViewOnloadContext.js
Labels: bug, 202504

#1601 build(deps): lock reset
  package-lock.json
Labels: build, 202504

#1591 fix(bannerMessages): sw-3519 modal detail for usage accounts
  public/locales/en-US.json
  src/components/README.md
  src/components/bannerMessages/__tests__/__snapshots__/bannerMessagesModal.test.js.snap
  src/components/bannerMessages/__tests__/bannerMessagesModal.test.js
  src/components/bannerMessages/bannerMessages.js
  src/components/bannerMessages/bannerMessagesModal.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/productView/__tests__/__snapshots__/productViewOnloadContext.test.js.snap
  src/components/productView/__tests__/productViewOnloadContext.test.js
  src/components/productView/productViewOnloadContext.js
  tests/__snapshots__/dist.test.js.snap
Labels: 202504

#1605 chore(release): 4.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 202504, 202508

#1603 feat(config): sw-3512 activate rhacm
  config/cspell.config.json
  public/locales/en-US.json
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/productView/__tests__/__snapshots__/productViewMissing.test.js.snap
  src/config/README.md
  src/config/__tests__/__snapshots__/product.config.test.js.snap
  src/config/__tests__/__snapshots__/products.test.js.snap
  src/config/product.rhacm.js
  src/config/products.js
  src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap
  src/services/rhsm/rhsmConstants.js
  tests/__snapshots__/code.test.js.snap
  tests/__snapshots__/dist.test.js.snap
Labels: 202504, 202508

#1606 fix(config): sw-3519 instances tooltip for billing accounts
  public/locales/en-US.json
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap
  src/components/tooltip/tooltip.js
  src/config/__tests__/__snapshots__/product.config.test.js.snap
  src/config/product.ansible.js
  src/config/product.openshiftDedicated.js
  src/config/product.openshiftMetrics.js
  src/config/product.rhacm.js
  src/config/product.rhacs.js
  src/config/product.rhelElsPayg.js
  src/config/product.rhods.js
  src/config/product.rosa.js
  src/services/rhsm/rhsmServices.js
  src/styles/_tooltip.scss
Labels: 202504, 202508

#1614 chore(release): 4.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 202508

#1618 fix(config): sw-3618 use vCPUs for rhacm
  public/locales/en-US.json
  src/config/__tests__/__snapshots__/product.config.test.js.snap
  src/config/product.rhacm.js
Labels: bug, 202508
